---

services:
  redis:
    image: redis:latest
    container_name: redis_container
    restart: unless-stopped
    volumes:
      - redis_peerapi_data:/data

  peerapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: peerapi
    restart: unless-stopped
    depends_on:
      - redis
    dns:
      - 172.20.0.53        # dn42-dns
      - 8.8.8.8
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./config.js:/usr/src/app/config.js
      - ./auth42-cred:/data/auth42-cred
      - /var/log/peerapi:/usr/src/app/logs
    ports:
      - "3000:3000/tcp"     # HTTP API
      - "2189:2189/udp"     # 探针服务器

volumes:
  redis_peerapi_data:
