# *******************************************************************
# docker-compose.yml
#
# Copyright (C) 2024 iEdon
# Copyright (C) 2026 Luochancy
#
# This file is part of a project derived from iedon-net-api.
# Modified by Luochancy on 2026-06.
#
# Licensed under the GNU General Public License v3.0.
# See the LICENSE file in the project root for details.
# *******************************************************************
---

services:
  redis:
    image: redis:latest
    container_name: redis_container
    restart: unless-stopped
    network_mode: host
    volumes:
      - redis_peerapi_data:/data

  peerapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: peerapi
    restart: unless-stopped
    network_mode: host
    depends_on:
      - redis
    volumes:
      - ./config.js:/usr/src/app/config.js
      - ./auth42-cred:/data/auth42-cred
      - /var/log/peerapi:/usr/src/app/logs

volumes:
  redis_peerapi_data:
